### ISSUE TITLE
Unable to install via Helm

### ISSUE THREAD

**Issue by wshelley** [kubeapps/kubeapps#1185]
On a new RBAC kube cluster I get the following errors on installation:

Looks like some kind of CRD race condition?

```
$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps

Error: unable to decode "": no kind "AppRepository" is registered for version "kubeapps.com/v1alpha1"


$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps

Error: apprepositories.kubeapps.com "bitnami" already exists


$helm version

Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by wshelley** [comment]
If I delete the CRD object it goes back to the original error:
```
$ kubectl delete AppRepository bitnami -n kubeapps
apprepository.kubeapps.com "bitnami" deleted


$ helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
Error: unable to decode "": no kind "AppRepository" is registered for version "kubeapps.com/v1alpha1"
```

**Comment by andresmgot** [comment]
hi @wshelley, we have just merged a PR that removes compatibility with Helm < 2.14. Would you mind upgrading to the latest version of Helm?

**Comment by wshelley** [comment]
Installed fine after the upgrade thank you.

Version number in docs may need to updated in that case: https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md

**Comment by andresmgot** [comment]
good catch, thanks for the heads up

**Comment by prashankprince** [comment]
Upgraded helm to v2.15.0 , still getting error:

sudo helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
Error: apprepositories.kubeapps.com "bitnami" already exists

helm version
Client: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.15.0", GitCommit:"c2440264ca6c078a06e088a838b0476d2fc14750", GitTreeState:"clean"}
