### ISSUE TITLE
Exposing dashboard without local proxy.

### ISSUE THREAD

**Issue by caseeker** [kubeapps/kubeapps#170]
Hello, I'm wondering if there's a way to expose the dashboard without running `kubeapps dashboard`.

I'm planning to setup a dev cluster and install kubeapps, and give developers access to kubeapps dashboard.

I'm running my cluster in AWS, and by making dashboard service to be load balancer, I could get to access the UI but none of the contents, like package deployment and existing deployments, are showing.

**Comment by prydonius** [comment]
Hey @caseeker! You can do this, but you need to make the `nginx-ingress` service a LoadBalancer service rather than `kubeapps-dashboard-ui`. That service in Kubeapps' own ingress and is what `kubeapps dashboard` proxies to.

Just FYI, we have authentication (via Kubernetes RBAC) on the roadmap which intends to make the setup you're trying to achieve much more secure. Currently, anyone who has access to the Dashboard has the permission to install charts, create functions and provision/bind Service Catalog instances in **any** namespace. That's probably fine for a dev cluster, but just wanted to give you the heads up that RBAC is coming soon which will make this a lot better.

**Comment by caseeker** [comment]
@prydonius thank you so much for quick help!
Now I can see the charts after exposing nginx-ingress, but I get following error when I try to deploy from the exposed dashboard.

> SyntaxError: Unexpected token < in JSON at position 0

I could successfully deploy charts with `kubeapps dashboard`, I couldn't find much logs that caused above error from pods yet.

**Comment by prydonius** [comment]
@caseeker huh, strange. Could you check the network tab in your browser's developer tools to see if any API requests look odd?

**Comment by caseeker** [comment]
@prydonius  the post request to /api/kube/apis/helm.bitnami.com/v1/namespaces/default/helmreleases is getting 403

**Comment by MnrGreg** [comment]
@prydonius @caseeker I've also been trying to expose the dashboard through an ingress. Would make a great sandbox for teams to play with!

I can access /api/chartsvc (chartsvc) and /kubeless (kubeless-ui) fine but /api/kube (kubeapps-kube-api) comes back with 403 Unauthorized (see screen grab).

The trace was performed on the nginx-controller which is forwarding the request and doesn't seem to be the issue. What authorization does kubeapps-kube-api require?

<img width="808" alt="screenshot" src="https://user-images.githubusercontent.com/24388819/37196309-31767488-232b-11e8-832a-81fcb08678bc.png">

Kubernetes version v1.9.3
helm version v2.8.1
Kubeapps Installer version: v0.4.0

**Comment by prydonius** [comment]
Interesting, thanks for the detailed trace @MnrGreg. The only thing I can think of is that the Kubernetes API is now being called from a non-localhost address and that might be causing the auth error. I'll have to dig into this a bit.

**Comment by prydonius** [comment]
Okay, I can confirm that's the issue. Here's how to reproduce:

1. Add `127.0.0.1 kubeapps-local.test` to /etc/hosts
2. `kubeapps dashboard --port=5000`
3. Visit http://kubeapps-local.test:5000 and notice 403 errors against the Kubernetes API proxy

**Comment by prydonius** [comment]
Okay, `kubectl proxy` by default only accepts requests from localhost. To disable this, you need to edit the kube-api deployment and add the `--disable-filter=true` flag:

```
$ kubectl edit deploy kubeapps-kube-api
```

The args for the container should look like:
```
      - args:
        - proxy
        - --disable-filter=true
        - --address=0.0.0.0
        - --port=8080
```

@caseeker @MnrGreg let me know if this works for you. If it does, I'll add some documentation to describe how to expose the Dashboard. Kubeapps won't be setting that flag by default until we fully support an auth workflow, and lock down the Kubernetes API with a dummy default service account.

**Comment by MnrGreg** [comment]
@prydonius adding the --disable-filter=true has worked. thanks

I was hoping to also use a central nginx controller in kube-system rather than the kubeapps nginx controller. When changing the ing/kubeapps kubernetes.io/ingress.class from"kubeapps-nginx" to "nginx" the central controller adds the config but one gets a 403 Forbidden now. I did add a host: match in the ingress rules as well. Do you think this might be possible to work around?

**Comment by prydonius** [comment]
@MnrGreg thanks for confirming! What version is your central nginx ingress controller? It might be because the annotations in 0.9.0 have changed and Kubeapps is still using an older (beta) version.

If I'm correct, you might just need to change `ingress.kubernetes.io/rewrite-target` to `nginx.ingress.kubernetes.io` for the two annotations we're using.

**Comment by MnrGreg** [comment]
@prydonius changing the annotations worked. Set them as per your suggestions below:
      "nginx.ingress.kubernetes.io/rewrite-target": "/",
      "nginx.ingress.kubernetes.io/ssl-redirect": "false"

I now have a single ingress for both the charts and kubeapps.

thank you

**Comment by caseeker** [comment]
@prydonius I also confirmed that `- --disable-filter=true` works. Thank you so much!

**Comment by spacecat** [comment]
I also confirm making the nginx-ingress service a LoadBalancer and setting - --disable-filter=true works. Thanks!

**Comment by MnrGreg** [comment]
@prydonius I've noticed there is more work happening to expose the dashboard externally. One thing that still seems to be an issue is the downgrading from https on the ingress controller to ws on the backend. This causes some browsers to block the Applications page.

<img width="917" alt="screengrab" src="https://user-images.githubusercontent.com/24388819/38451777-d73336b0-39ea-11e8-9cef-4505f4740c9e.png">

`main.ace90388.js:1 Mixed Content: The page at 'https://kubeapps.$$$$/apps/default/default-rabbitmq-ha' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://kubeapps.$$$$/api/kube/api/v1/namespaces/default/services?watch=true&fieldSelector=metadata.name%3Ddefault-rabbitmq-ha-rabbitmq-ha'. This request has been blocked; this endpoint must be available over WSS.`

**Comment by prydonius** [comment]
@MnrGreg ah interesting, hopefully this is just a matter of figuring out the current scheme (http or https) and deciding to use ws or wss. I'll look into this, thanks! Created #233

**Comment by jmo808** [comment]
I did not get the mixing of insecure resources when I changed the kubeapps ingress manifest to use my cluster wide implementation of nginx-ingress (in combination with kube-lego and external-dns). I used oauth2-proxy to secure access to the dashboard/api/kubeless. This is a pattern that I've used over and over again to have secure external access to web apps.

**Comment by prydonius** [comment]
@jmo808 nice, I was planning on writing some documentation on how to setup oauth2-proxy with Kubeapps at some point. It'd be great if you wanted to help with that!

I am curious why you didn't run into #233 though, maybe it's a browser setting?

**Comment by jmo808** [comment]
Yeah, I think it is a browser issue. I discovered later than firefox just blocks any offending content silently. It didn’t affect the functioning of the site though.

I can help with documentation if you’d like. The nginx-ingress – oauth2-proxy pattern is pretty common.

I combine oauth2-proxy – nginx-ingress with external-dns and kube-lego (or cert-manager if you want)

**Comment by prydonius** [comment]
@MnrGreg @jmo808 the websocket issue should now be fixed in the latest release (v0.7.0+)!

**Comment by Omniscience619** [comment]
After redeploying the latest Kubeapps chart on my cluster, I received this error on Google Chrome.

```
2.7529bf57.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
main.b2ea2d43.chunk.js:1 Uncaught SyntaxError: Unexpected token '<'
```
As I went through this thread, I noticed someone saying that Firefox might block some offending parameter. I decided to give it a try on Mozilla Firefox, since in my case it's giving an error on Google Chrome, and it worked.

I still don't know why exactly it's behaving this way though.

**Comment by absoludity** [comment]
Hi @Omniscience619 . The 404 you're seeing is just kubeapps checking if the operator lifecycle manager is installed, it's not an issue at all. The original issue that you saw (but that disappeared) could be because the services weren't yet up and running... not sure without more info. But if you can reproduce it and want further investigation, please open a *new* issue. Thanks.
