### ISSUE TITLE
Better handling of configured plugins and their dependencies

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#4264]
### Description:

Our Kubeapps-APIs service can be configured to run with different plugins (currently `fluxv2`, `kapp-controller`, `helm` and `resources`), which enables those plugins to be loaded at runtime. The fluxv2 plugin depends on having redis available, as the helm plugin depends on postgres (as do other parts). The resources plugin is always required for Kubeapps.

Currently the kubeapps-apis service plugins are explicitly enabled by setting the list of `kubeappsapis.enabledPlugins`, while their dependencies, such as redis for fluxv2, need to be enabled separately. Or related to this, as the resources plugin is always required , users can currently mis-configure Kubeapps (eg. #4259 ). This should not be possible.

I'd like to update this so that instead, as a user, we can enable fluxv2 support for Kubeapps (I don't care about some kubeappsapis sub-service), and both the kubeapps-apis plugins as well as the redis enablement will be set automatically.

### Additional information you deem important (e.g. issue happens only occasionally):

Helm subcharts can be conditionally included based on either a valid value in the `values.yaml` (eg. `featureFlags.fluxv2.enabled` or similar), or a tag. See [conditions and tags](https://helm.sh/docs/chart_best_practices/dependencies/#conditions-and-tags). The condition cannot be anything calculated (such as a helper).

As such, one solution would be that we remove the ability to configure the kubeapps-apis plugins directly, and instead expose something like the following at the top level of the chart values:

```
plugins:
  helm:
    enabled: true
  flux:
    enabled: false
  carvel:
    enabled: false
```
(note that this means we can expose the kapp-controller plugin simply as `carvel` as we previously wanted to... so users can "enable carvel support in Kubeapps", or similarly, flux support and we enable the fluxv2 plugin). 

This would enable us to:
1. automatically include any required subcharts conditionally,
2. calculate the actual plugins required for kubeapps-apis, in addition to the required resources plugin,
3. provide simple user feature names (eg. "carvel" or "flux").
4. we could also move the configuration to this top level also?

Thoughts?

**Comment by absoludity** [comment]
Tested initial idea at #4265

**Comment by castelblanque** [comment]
It sounds like a good idea! It would make installation easier for users, and Kubeapps would have more control over what (and how) is installed as dependency (redis, postgres, etc.). This should mean less potential issues when installing (e.g. incompatible redis version, etc.).

> 1. automatically include any required subcharts conditionally,
    
+1 That would be solved with some templating in the helm chart, wouldn't it?
    
>  2. calculate the actual plugins required for kubeapps-apis, in addition to the required resources plugin,
    
+1 except for the resources plugin, I see it a bit differently. Why is it set as a plugin when Kubeapps can not start up without it? Should it even appear in the chart in that case? There is no configuration that users can customize either (maybe I'm missing something here), so why bubbling that up to the chart?
    
> 3. provide simple user feature names (eg. "carvel" or "flux").
    
+1 For the users is better to use simple and easily known names rather than technically correct ones. Inside Kubeapps we can use the right ones (e.g. kapp).

> 4. we could also move the configuration to this top level also?
    
I see that structure as a representation of what is implemented, but maybe for ease of use abstracting the user away from the "plugins" concept would be simpler? Something like e.g.

```
helm:
  enabled: true
flux:
  enabled: false
carvel:
  enabled: false
```
Also using `featureFlags.*` as you propose would be more meaningful for the user.

**Comment by absoludity** [comment]
> > 1. automatically include any required subcharts conditionally,
> 
> +1 That would be solved with some templating in the helm chart, wouldn't it?

It's solved by providing a boolean value in the values.yaml which can be referred to in the dependency condition. The helm format for conditionals there can only refer to a value (I tried using a template helper so we could use the existing format of a list of plugins, but it needs to be a straight value). See the example in the linked PR

> 
> > 2. calculate the actual plugins required for kubeapps-apis, in addition to the required resources plugin,
> 
> +1 except for the resources plugin, I see it a bit differently. Why is it set as a plugin when Kubeapps can not start up without it? Should it even appear in the chart in that case? There is no configuration that users can customize either (maybe I'm missing something here), so why bubbling that up to the chart?

Yep, the proposal here is that the user doesn't have to add the resources plugin at all, for the reasons you mention. Again, see the example in the linked PR. Note that it is still a separate plugin in the sense that another project could run the kubeapps apis service *without* the resources plugin if they wanted (because their UI doesn't expose k8s resources at all - the packaging plugins work without it). But here for Kubeapps, we do require it, hence making it always configured in the linked PR without the user needing to care.


> 
> > 3. provide simple user feature names (eg. "carvel" or "flux").
> 
> +1 For the users is better to use simple and easily known names rather than technically correct ones. Inside Kubeapps we can use the right ones (e.g. kapp).
> 
> > 4. we could also move the configuration to this top level also?
> 
> I see that structure as a representation of what is implemented, but maybe for ease of use abstracting the user away from the "plugins" concept would be simpler? Something like e.g.
> 
> ```
> helm:
>   enabled: true
> flux:
>   enabled: false
> carvel:
>   enabled: false
> ```
> 
> Also using `featureFlags.*` as you propose would be more meaningful for the user.

So possibly:

```
featureFlags:
  helm: true
  flux: false
  carvel: false
```
? And yes, I agree that from a users' POV, `featureFlags` makes sense. We'd used that as a feature gate for new features in the past until they were available for everyone, but in a sense, these features are similar, just never available to everyone by default.

Let's see what @antgamdia thinks too. Thanks for the feedback and thought Rafa!

**Comment by antgamdia** [comment]
Thank you, Michael, for the proposal. As the number of plugins starts to grow, it's important to abstract users (as well as clumsy devs like me :P) from this complexity.

I agree with the overall approach you sketched out in the PR, but I'd still have a couple of thoughs:

- Are we creating the `kubeapps.kubeappsapis.enabledPlugins`  field from scratch solely by means of a tpl helper? If so , what if another dev wants to add another plugin? Wouldn't they need to also modify the helper file instead of just the values.yaml?
    -  Ideally, as an advanced user, I'd like to disable helm, carvel and flux, and instead just add `myCoolPlugin`. Would it still be possible after your PR? 
    - Maybe, a `.kubeappsapis.advancedPluginConfig: true` could disable this helper and allow users to set the array manually. If they want to enable helm, they still should set `packaging.helm.enabled: true` -and- also define `kubeappsapis.enabledPlugins[0]=helm`
- I don't think we should have root-level things like `.helm.enabled` etc, since, in the end, they all belong to the same "packaging/packages" concept. Perhaps `.packaging.helm.enabled` could also work.

Anyway, +1 as it solves a real UX problem we have.

**Comment by absoludity** [comment]
>     * Are we creating the `kubeapps.kubeappsapis.enabledPlugins`  field from scratch solely by means of a tpl helper? If so , what if another dev wants to add another plugin? Wouldn't they need to also modify the helper file instead of just the values.yaml?

Yes, although I was wanting to keep this backwards compatible so was planning to use the value from `kubeapps.kubeappsapis.enabledPlugins` if it has been manually set, but change it's default to empty, so that it is written by the helper.

>       
>       * Ideally, as an advanced user, I'd like to disable helm, carvel and flux, and instead just add `myCoolPlugin`. Would it still be possible after your PR?
>       * Maybe, a `.kubeappsapis.advancedPluginConfig: true` could disable this helper and allow users to set the array manually. If they want to enable helm, they still should set `packaging.helm.enabled: true` -and- also define `kubeappsapis.enabledPlugins[0]=helm`

Do you think if we document the `kubeappsapis.enabledPlugins` field such that it defaults to "" and the plugins are configured automatically, but if you choose to set it, that takes precedence? I'll update the PR to show what I mean.

> 
>     * I don't think we should have root-level things like `.helm.enabled` etc, since, in the end, they all belong to the same "packaging/packages" concept. Perhaps `.packaging.helm.enabled` could also work.

OK, currently I've got `plugins.helm.enabled` etc., but will switch to `packaging`, as again, it's irrelevant to the user whether it's a plugin or not.

> 
> 
> Anyway, +1 as it solves a real UX problem we have.

Great, thanks.
