### ISSUE TITLE
Chart file metadata doesn't change for same version numbers

### ISSUE THREAD

**Issue by ddseapy** [kubeapps/kubeapps#659]
When pushing charts with same version (ie, 0.1.0-SNAPSHOT), the chart updates correctly after refreshing the repo however the values.yaml is the old values.yaml.

This can be misleading and is a bit painful when developing charts, unless you bump versions every time you push changes to values.yaml.  Doesn't appear to be cached in browser, so I think it's cached in kubeapps.  Tested with both artifactory and chartmuseum.

**Comment by prydonius** [comment]
@ddseapy ah yes, this is cached in MongoDB. I'm torn on this, on one hand I understand that it's misleading and painful if your workflow is to push the same version. On the other hand, being able to cache these for the chart versions that Kubeapps has previously seen greatly improves the speed of subsequent syncs of chart repositories. Refetching the fresh values.yaml and README each time will require us to always download the chart tarballs for each and every version.

However, this is because we're currently using the chart version as they key, it would actually make more sense to use the chart's `digest` as a key and only re-download values/README if that changes. That would give us the benefit of both worlds as, in your workflow, that digest would change even if the version stays the same. Does that make sense?

@migmartri @andresmgot WDYT?

**Comment by prydonius** [comment]
FYI this is where this is happening:

https://github.com/kubeapps/kubeapps/blob/0a675559078d5a9b987770ae9baa7c5f70109c8f/cmd/chart-repo/utils.go#L318-L320, where chartFilesID is a concatenation of the repo name, chart name and chart version.

**Comment by ddseapy** [comment]
Yep, that makes sense.  Thanks for the explanation.

**Comment by migmartri** [comment]
Thanks @ddseapy for reporting the issue!

> I'm torn on this, on one hand I understand that it's misleading and painful if your workflow is to push the same version. On the other hand, being able to cache these for the chart versions that Kubeapps has previously seen greatly improves the speed of subsequent syncs of chart repositories.

The issue here is that if we do not want to fetch the same version (because of technical optimization), we should at least let the user know that we detected a possible override. Making this behavior silent does not seem to be a good option since it is masking the impact of the problem (people that did not notice that the readme and values.yaml are outdated).

That said, I would not implement and override notification but instead a content addressable reference via its sha as you suggested @prydonius

**Comment by andresmgot** [comment]
Using the checksum as ID sounds good to me 👍

**Comment by prydonius** [comment]
## Current State

- IDs the in the chart files collection are made up of `$repo_name/$chart_name-$chart_version`
- We check if an entry with that ID exists, if it does we skip fetching the tarball/README
- When deleting a repository, we remove all chart file entries with the repo name attribute equal to the repo being deleted
- chartsvc gets the values/README files using the repo name, chart name and version passed as URL parameters, it doesn't first fetch the chart metadata itself

## Proposal A

The simplest thing to do would be to store the digest as an attribute under the chart files collection:

```diff
type chartFiles struct {
        Readme string
        Values string
        Repo   repo
+       Digest string
 }
```

With this stored, we adapt our skip logic to only skip if the digest is the same, otherwise continue.
https://github.com/kubeapps/kubeapps/blob/0a675559078d5a9b987770ae9baa7c5f70109c8f/cmd/chart-repo/utils.go#L318-L320

The benefit of this is that it avoids changing the ID which will require additional changes in chartsvc.

### Upgrades

Since the digest will only be stored by newer versions of the `chart-repo` tool, the first time it is run it will refetch all the tarballs for all chart versions. However, since the ID will be the same, a forced resync is not required on upgrade.

## Proposal B

Alternatively, we can decide to change the ID to include the digest instead of the chart name and version.

Since multiple repositories can have the same chart versions and so exact same digests, we will include the repo name in the ID. This is to avoid deleting chart files that another repository might be relying on if the ID is solely made up of the digest.

chartsvc will need to be modified to first fetch the chart version requested (from the URL params) to get the digest, and then fetch the chart files using the digest.


A fallback of this approach is that old chart files for the same chart version will be kept behind if the digest changes, with no way to clean up unless the repository is deleted. This could potentially leave a lot of unnecessary artefacts behind.

## Upgrades

New versions of the chartsvc will not find chart files until they have been resynced with the new IDs. This will require us to force a resync during the upgrade process.

---

@migmartri @andresmgot what do you think of the above two proposals? I personally think there isn't really a benefit of doing B apart from the digest being a more "correct" key to use. To fix this issue, I would suggest doing the simple thing (A), we can park the digest as key idea until there is a future need to do so (e.g. we need to store files for package types other than charts).

**Comment by andresmgot** [comment]
I agree with @migmartri and you, I'd go for option A.

**Comment by prydonius** [comment]
Sounds good, thanks - I'll start working on that

**Comment by prydonius** [comment]
@ddseapy this should be fixed in the latest release (v1.0.0-beta.4), it would be great if you could give it a try and let us know if it works for you!

**Comment by ddseapy** [comment]
@prydonius Thanks a bunch!  I'll upgrade Kubeapps on Monday and will let you know.

**Comment by ddseapy** [comment]
Bumped to v1.0.0-beta.4 and tried pushing changes to values.yaml under the same version.  If I remove and re-add the repo the values.yaml is updated, however when simply refreshing the repo it still shows the old values.yaml.

A couple nitpicky things I noticed, hardly worth mentioning:

* When adding a repo you still need to refresh the repo to get charts to show up.  Maybe there is use case for just adding a repo without loading the charts, just might be a bit odd to new users.
* The date on the chart is the creation date, instead of last update time.

All that said, it works fine.  It's not that hard to delete+add+refresh repo, just a bit more involved than just a refresh.

Thanks!

**Comment by migmartri** [comment]
Thanks @ddseapy!

> If I remove and re-add the repo the values.yaml is updated, however when simply refreshing the repo it still shows the old values.yaml.

This is strange, I believe that this should not be the case, it might be a bug. @prydonius can you confirm?

> When adding a repo you still need to refresh the repo to get charts to show up. Maybe there is use case for just adding a repo without loading the charts, just might be a bit odd to new users.

Strange, I do not think that it should be the case. For example, I just added a new repository from the UI and I can see a new CRD and a job that got scheduled. Could you confirm that this is not the case for you? Thanks!

```bash
k get apprepositories.kubeapps.com mynewrepo
NAME        CREATED AT
mynewrepo   26s

$ k get jobs
NAME                           DESIRED   SUCCESSFUL   AGE
apprepo-sync-mynewrepo-2b7j4   1         0            44s
```

> The date on the chart is the creation date, instead of last update time.

This is a good point. I guess that one question that we need to answer is? Should we make the use case of mutating a packaged version a first class citizen or an exception? The other question would be, is there any downside of using updated_at instead of created_at in either scenario (people that always bump the chart version and people that might mutate an existing version). If not, I'd be in favor of using the updated_at timestamp.

Thank you for the detailed piece of feedback @ddseapy! 

cc/ @prydonius @andresmgot

**Comment by dseapy** [comment]
@migmartri You are correct.  Looks like it's being cached in my browser... opening it up incognito window fixes the issue.  Sorry about that.

Clearing cache doesn't seem to update the values.yaml unfortunately.

**Comment by prydonius** [comment]
@dseapy just to clarify, when you use incognito you always see the new values? When not in incognito, do you see any cache headers in the request for the values.yaml file?

>> When adding a repo you still need to refresh the repo to get charts to show up. Maybe there is use case for just adding a repo without loading the charts, just might be a bit odd to new users.
>
> I do not think that it should be the case. For example, I just added a new repository from the UI and I can see a new CRD and a job that got scheduled. Could you confirm that this is not the case for you? Thanks!

@migmartri is correct that you shouldn't need to hit refresh, can you verify that you're still seeing this issue?

> The date on the chart is the creation date, instead of last update time.

As far as I know, there is no last update time stored in the chart repository index? I can only see the `created` timestamp. Is there something I'm missing?

**Comment by ddseapy** [comment]
I apologize, I think I've added some confusion.  Basically 3 things I mentioned:

1. Values.yaml not updating when refreshing repo  - This still appears to be an issue but has a workaround by deleting/re-creating the repo
2. Needing to hit refresh to view charts for new rep - This was my mistake (browser was caching results) and is not an issue, @migmartri is correct.
3. Create timestamp being shown - what you say makes sense, feel free to disregard what I said.

**Comment by prydonius** [comment]
@ddseapy no worries, thanks for clarifying!

> Values.yaml not updating when refreshing repo - This still appears to be an issue but has a workaround by deleting/re-creating the repo

Does this happen every single time you update your chart? Let me know if you have some steps I can use to reproduce this.

**Comment by ddseapy** [comment]
I tried a few times and it has happened every time thus far.

1. push a chart to private chart repo from a local dir
2. view the chart values.yaml in kubeapps (go to deploy... don't need to deploy it)
3. add a comment line to the values.yaml for the chart locally (to be used to differentiate this from the original chart pushed)
4. Repeat step 1
5. Refresh your chart repo in kubeapps
6. Repeat step 2  -- This will show the same values.yaml seen in step 2 (without the added comment)

Replacing step 5 with delete+create repo provides updated values.yaml in step 6.
I can provide exact commands tomorrow if helpful.

**Comment by migmartri** [comment]
This is extremely useful @ddseapy, I am going to look into it. 

Thanks for taking the time of reporting it.

**Comment by prydonius** [comment]
@ddseapy @migmartri and I were not able to reproduce this with the latest version of the chart (from a clean install). Can you confirm your syncs are running with the `quay.io/helmpack/chart-repo:v1.0.1` image and chartsvc is running `quay.io/helmpack/chartsvc:v1.0.1`?

A quick way to check is by running `kubectl get po -o yaml | grep image:` in the namespace you installed Kubeapps into.

**Comment by dseapy** [comment]
Not sure if relevant, but some more info:
We are using kubeapps-0.9.4 chart, with only change being frontend.service.type=NodePort  (no cloud provider).  The private chart repo is added through the ui after kubeapps installation, not in the chart.

**Comment by prydonius** [comment]
@dseapy hmm, that version looks good. Can you start a sync in debug mode and paste the logs? You can run the following Pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: apprepo-debug-sync
spec:
  restartPolicy: OnFailure
  containers:
  - args:
    - sync
    - --debug
    - --mongo-url=kubeapps-mongodb
    - --mongo-user=root
    - $YOUR_REPO_NAME
    - $YOUR_REPO_URL
    command:
    - /chart-repo
    env:
    - name: MONGO_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: kubeapps-mongodb
    image: quay.io/helmpack/chart-repo:v1.0.1
    name: sync
```

Make sure to change $YOUR_REPO_NAME and $YOUR_REPO_URL for your repository. Then paste the output of `kubectl logs apprepo-debug-sync`.

**Comment by dseapy** [comment]
Hopefully tomorrow I'll be able to try again.  For some reason any call to kubectl logs for sync/cleanup pods is coming back empty (including the pod with debug configuration you provided).  Not sure why, or what changed.  I did a delete --purge on kubeapps, deleted the namespace and reinstalled kubeapps... didn't help.  Everything is still running the same, just the job pods aren't logging.

Just in case it was an issue I tried changing my Chart version to sem2 versioning since mine are complex sem2 (https://github.com/helm/helm/blob/master/docs/charts.md#charts-and-versioning), but didn't help.

**Comment by prydonius** [comment]
@dseapy strange, are you seeing charts populated in the UI? That would at least indicate that the syncs are actually completing and not just hanging.

**Comment by ddseapy** [comment]
Yeah, charts show up.  There is no change in behavior other than no logs are shown.  All sync/cleanup pods show status as completed on a kc get po.

I tried a refresh in the UI and looked at the log for another (non-sync) pod, can't remember the name since I am out of office now, but it even mentioned the sync completed successfully.  They are definitely running.

**Comment by prydonius** [comment]
@ddseapy hmm now I'm a little lost, you mentioned you're seeing the "sync completed successfully" in the log, but not seeing other log messages?

**Comment by dseapy** [comment]
Haven't had time today to dig in more.  Originally I was able to view logs of sync pods, but yesterday they started coming back empty and that's what I was trying to figure out.

In an effort to figure out what was going on (and if it was just an issue with the sync pods) I looked at the logs of the other pods.  One of those seemed to log syncs as successful when I tried refreshing a repo in the UI.  Think it was a controller or something, but don't recall exactly.  Regardless I don't know that it helps me figure out what's going on.

Kubernetes itself seems fine (ie. no full disks or anything).  I'm guessing the next step is for me to dig into the code a bit and try to figure out why logging isn't showing anymore for sync pods. Not sure what else to try.

**Comment by prydonius** [comment]
@dseapy ah you might have been looking at the apprepository-controller logs, the logs there don't actually reflect whether a chart repository has been synced or not. Unfortunately I can't really reproduce this on my environment... although the fact that you are seeing charts means the sync _is_ happening. Is there another cluster you can try to reproduce this on?

**Comment by dseapy** [comment]
Yeah, I can upgrade kubeapps on the other cluster and give it a shot there but probably not this week.

**Comment by prydonius** [comment]
@dseapy great, no worries, let us know if you make any progress!

**Comment by migmartri** [comment]
Hi @dseapy 

Did you manage to give it a try, please let us know if you are still running into this issue.

Thanks,
Miguel

**Comment by dseapy** [comment]
I'm afraid I haven't really had much time lately to dig in further or try it out on the other cluster.  As we have a workaround there have been other higher-priority tasks.  When I get back to this I'll add a comment with any new info.

**Comment by dseapy** [comment]
fwiw logging issue was unrelated to kubeapps as it was the result of journald rate limiting (https://github.com/moby/moby/issues/31058#issuecomment-295752609).  Another docker running on that cluster was outputting tons of logs.
